import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Toaster } from 'react-hot-toast';
import ContainerUI from '<spoon>/components/ui/container-ui';
import Header from '<spoon>/components/ui/header-ui';
import FooterUI from '<spoon>/components/ui/footer-ui';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Spoon',
  description: 'Generated by Spoon',
}

export default function RootLayout({children,}: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ContainerUI className='relative space-y-6' >
          <Header />
            <main>
              <ContainerUI>
                {children}
              </ContainerUI>
            </main>
          <Toaster position='top-right' />
          <FooterUI />
        </ContainerUI>
      </body>
    </html>
  )
}
